### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by ashraf-patel** [fbsamples/account-kit-samples-for-android#15]
I am facing this issue in my one project. I've used Account kit before and at that time I faced no problem. I am not able to figure out whats the issue here.

`/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.letsdogether.dogether, PID: 24444
                                                                           java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Lcom/google/android/gms/common/api/Api;Lcom/google/android/gms/common/api/Api$ApiOptions;Lcom/google/android/gms/internal/zzbel;)V in class Lcom/google/android/gms/common/api/GoogleApi; or its super classes (declaration of 'com.google.android.gms.common.api.GoogleApi' appears in /data/app/com.letsdogether.dogether-2/base.apk:classes29.dex)
                                                                               at com.google.android.gms.auth.api.phone.SmsRetrieverClient.<init>(Unknown Source)
                                                                               at com.google.android.gms.internal.zzash.<init>(Unknown Source)
                                                                               at com.google.android.gms.auth.api.phone.SmsRetriever.getClient(Unknown Source)
                                                                               at com.facebook.accountkit.internal.PhoneLoginController.createSmsToken(PhoneLoginController.java:250)
                                                                               at com.facebook.accountkit.internal.PhoneLoginController.logIn(PhoneLoginController.java:188)
                                                                               at com.facebook.accountkit.internal.LoginManager.logInWithPhoneNumber(LoginManager.java:372)
                                                                               at com.facebook.accountkit.internal.AccountKitController.logInWithPhoneNumber(AccountKitController.java:627)
                                                                               at com.facebook.accountkit.ui.PhoneLoginFlowManager.logInWithPhoneNumber(PhoneLoginFlowManager.java:57)
                                                                               at com.facebook.accountkit.ui.ActivityPhoneHandler.onPhoneLoginComplete(ActivityPhoneHandler.java:189)
                                                                               at com.facebook.accountkit.ui.AccountKitActivity$1.onReceive(AccountKitActivity.java:176)
                                                                               at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
                                                                               at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
                                                                               at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                               at android.os.Looper.loop(Looper.java:207)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5750)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)`

**Comment by usama27** [comment]
Im facing same issue,

**Comment by ashraf-patel** [comment]
I've resolved the problem by specifying specific version of Account kit in build.gradle(app).

USE,
**compile 'com.facebook.android:account-kit-sdk:4.22.1'**

instead of 
compile 'com.facebook.android:account-kit-sdk:4.+'

**Comment by usama27** [comment]
Thank you  Ashraf patel, this also resolved my problem.
