### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by shashankpsingh** [fbsamples/account-kit-samples-for-android#16]
In my project, I am using libPhoneNumber library and account kit. After click on suggestion showing in account kit it crashes and gave me those logs.

I am using latest account kit lib version i.e 4.27.0 and libPhoneNumber version 8.8.4.
Listing Error Log.

`11-01 15:26:28.801 16271-16271/com.ela.android E/UncaughtException: java.lang.NoSuchMethodError: No virtual method parse(Ljava/lang/String;Ljava/lang/String;)Lcom/google/i18n/phonenumbers/Phonenumber$PhoneNumber; in class Lcom/google/i18n/phonenumbers/PhoneNumberUtil; or its super classes (declaration of 'com.google.i18n.phonenumbers.PhoneNumberUtil' appears in /data/app/com.ela.android-2/base.apk:classes8.dex)
                                                                        at com.facebook.accountkit.internal.Utility.parseNumber(Utility.java:217)
                                                                        at com.facebook.accountkit.ui.PhoneLoginContentController.onActivityResult(PhoneLoginContentController.java:763)
                                                                        at com.facebook.accountkit.ui.AccountKitActivity.onActivityResult(AccountKitActivity.java:373)
                                                                        at android.app.Activity.dispatchActivityResult(Activity.java:6168)
                                                                        at android.app.ActivityThread.deliverResults(ActivityThread.java:3733)
                                                                        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3780)
                                                                        at android.app.ActivityThread.access$1300(ActivityThread.java:162)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                        at android.os.Looper.loop(Looper.java:189)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5530)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
`

**Comment by ashraf-patel** [comment]
checkout this 
https://github.com/fbsamples/account-kit-samples-for-android/issues/15
