### ISSUE TITLE
Facebook accout kit Firebase API initialization failure

### ISSUE THREAD

**Issue by girubhai** [fbsamples/account-kit-samples-for-android#18]
After implementing **Facebook Account Kit** and run project it shows  **Firebase API initialization failure** as

    FirebaseApp: Firebase API initialization failure.
     java.lang.reflect.InvocationTargetException
     at java.lang.reflect.Method.invoke(Native Method)
     at com.google.firebase.FirebaseApp.zza(Unknown Source)
     at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
     at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
     at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
     at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
     at android.content.ContentProvider.attachInfo(ContentProvider.java:1758)
     at android.content.ContentProvider.attachInfo(ContentProvider.java:1733)
     at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
     at android.app.ActivityThread.installProvider(ActivityThread.java:5257)
     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4808)
     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4748)
     at android.app.ActivityThread.access$1700(ActivityThread.java:153)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1436)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:154)
     at android.app.ActivityThread.main(ActivityThread.java:5529)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

And also getting **Null Pointer Exception** from **AccountKitController** as

    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
     at com.facebook.accountkit.internal.Initializer.initialize(Initializer.java:101)
     at com.facebook.accountkit.internal.AccountKitController.initialize(AccountKitController.java:601)
     at com.facebook.accountkit.internal.AccountKitInitProvider.onCreate(AccountKitInitProvider.java:31)
     at android.content.ContentProvider.attachInfo(ContentProvider.java:1758)
     at android.content.ContentProvider.attachInfo(ContentProvider.java:1733)
     at android.app.ActivityThread.installProvider(ActivityThread.java:5257)
     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4808) 
     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4748) 
     at android.app.ActivityThread.access$1700(ActivityThread.java:153) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1436) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:154) 
     at android.app.ActivityThread.main(ActivityThread.java:5529) 
     at java.lang.reflect.Method.invoke(Native Method) 

Using Account kit gradle as

    compile 'com.facebook.android:account-kit-sdk:4.27.0'

And Firebase Gradle as

    compile 'com.google.firebase:firebase-messaging:11.0.4'

Note : Removing Account Kit from project its working fine i.e. there is no **Firebase API initialization failure.** issue. Therefore it's sure that there is conflict in firebase and Account kit SDK (:

**Comment by byin** [comment]
Thank you for the report @girubhai, we're investigating the issue and will post updates on https://developers.facebook.com/bugs/313888152353002/

**Comment by girubhai** [comment]
@byin Thanks to reply. I think (not 100% sure) its an issue with multidex.

`    compile 'com.android.support:multidex:1.0.1'
`

**Comment by byin** [comment]
The fix will be included in the next SDK release. In the meantime, you can use the workaround described on https://developers.facebook.com/bugs/313888152353002/
