### ISSUE TITLE
Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by sohailniazai** [fbsamples/account-kit-samples-for-android#19]
I have been facing the crash in my app .. Following is the stacktrace of the crash: 

Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1280)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1291)
       at android.app.FragmentManagerImpl.popBackStack(FragmentManager.java:477)
       at com.facebook.accountkit.ui.StateStackManager.popBackStack(StateStackManager.java:132)
       at com.facebook.accountkit.ui.AccountKitActivity.popBackStack(AccountKitActivity.java:700)
       at com.facebook.accountkit.ui.ActivityPhoneHandler.popToPhoneNumberInput(ActivityPhoneHandler.java:214)
       at com.facebook.accountkit.ui.ActivityPhoneHandler.onResend(ActivityPhoneHandler.java:200)
       at com.facebook.accountkit.ui.AccountKitActivity$1.onReceive(AccountKitActivity.java:205)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
       at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:153)
       at android.app.ActivityThread.main(ActivityThread.java:5093)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
       at dalvik.system.NativeStart.main(NativeStart.java)

Kindly, help me with the solution

**Comment by ekeuus** [comment]
Same issue

**Comment by tulioccalazans** [comment]
Same issue.

`com.facebook.android:account-kit-sdk:4.27.0`
