### ISSUE TITLE
Phone number config crashes on tablets

### ISSUE THREAD

**Issue by alexandru1208** [fbsamples/account-kit-samples-for-android#21]
When i select phone, on every tablet it crashes with the this stack trace:

01-30 18:33:33.703 29074-29074/com.example.accountkitsimplesample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.example.accountkitsimplesample, PID: 29074
                                                                                    java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference
                                                                                        at android.widget.TextView.checkForRelayout(TextView.java:6834)
                                                                                        at android.widget.TextView.onRtlPropertiesChanged(TextView.java:8939)
                                                                                        at android.view.View.resolveRtlPropertiesIfNeeded(View.java:12998)
                                                                                        at android.view.View.measure(View.java:17424)
                                                                                        at android.widget.Spinner.setUpChild(Spinner.java:657)
                                                                                        at android.widget.Spinner.makeView(Spinner.java:610)
                                                                                        at android.widget.Spinner.getBaseline(Spinner.java:456)
                                                                                        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1120)
                                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
                                                                                        at com.facebook.accountkit.ui.ConstrainedLinearLayout.onMeasure(ConstrainedLinearLayout.java:114)
                                                                                        at android.view.View.measure(View.java:17430)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                                        at android.view.View.measure(View.java:17430)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                                        at com.facebook.accountkit.ui.ConstrainedLinearLayout.onMeasure(ConstrainedLinearLayout.java:97)
                                                                                        at android.view.View.measure(View.java:17430)
                                                                                        at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1260)
                                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                                        at android.widget.ScrollView.onMeasure(ScrollView.java:337)
                                                                                        at android.view.View.measure(View.java:17430)
                                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
                                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
                                                                                        at android.view.View.measure(View.java:17430)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                                        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                        at android.view.View.measure(View.java:17430)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                                        at android.view.View.measure(View.java:17430)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                                        at android.view.View.measure(View.java:17430)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                                        at android.view.View.measure(View.java:17430)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2560)
                                                                                        at android.view.View.measure(View.java:17430)
                                                                                        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2001)
                                                                                        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1166)
                                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1372)
                                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
                                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                                    	at android.os.Handler.handleCallback(Hand

**Comment by magic6ball** [comment]
@alexandru1208 We tried to repro this issue with the latest version (v4.30) and didn't see the crash. Please file a bug through https://developers.facebook.com/tools-and-support/ with more details.
