### ISSUE TITLE
ConstrainedLinearLayout Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by jamin0107** [fbsamples/account-kit-samples-for-android#22]
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference

       at android.widget.TextView.checkForRelayout(TextView.java:7104)
       at android.widget.TextView.onRtlPropertiesChanged(TextView.java:9271)
       at android.view.View.resolveRtlPropertiesIfNeeded(View.java:13302)
       at android.view.View.measure(View.java:17910)
       at android.widget.Spinner.setUpChild(Spinner.java:663)
       at android.widget.Spinner.makeView(Spinner.java:616)
       at android.widget.Spinner.getBaseline(Spinner.java:462)
       at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1288)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:631)
       at com.facebook.accountkit.ui.ConstrainedLinearLayout.onMeasure(SourceFile:114)
       at android.view.View.measure(View.java:17917)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
       at android.view.View.measure(View.java:17917)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
       at com.facebook.accountkit.ui.ConstrainedLinearLayout.onMeasure(SourceFile:97)
       at android.view.View.measure(View.java:17917)
       at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1286)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
       at android.widget.ScrollView.onMeasure(ScrollView.java:342)
       at android.view.View.measure(View.java:17917)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:846)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:512)
       at android.view.View.measure(View.java:17917)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(SourceFile:139)
       at android.view.View.measure(View.java:17917)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
       at android.view.View.measure(View.java:17917)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
       at android.view.View.measure(View.java:17917)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
       at android.view.View.measure(View.java:17917)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2731)
       at android.view.View.measure(View.java:17917)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2416)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1418)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1642)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1296)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6602)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
       at android.view.Choreographer.doCallbacks(Choreographer.java:603)
       at android.view.Choreographer.doFrame(Choreographer.java:572)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

last week we update facebook sdk to 4.30.0
      `compile 'com.facebook.android:facebook-login:4.30.0'`
      `compile 'com.facebook.android:account-kit-sdk:4.30.0'`
and find the bug  in fabric.
and its  first in rank.
please help ^^

**Comment by abhas9** [comment]
Facing the same issue. All the crashes are in Android 5.X

I have opened a bug. Please follow at: https://developers.facebook.com/bugs/146171089525966/

**Comment by fabredthunder** [comment]
No news with that issues ?!
It keeps on crashing again and again on some old devices ...
