### ISSUE TITLE
Not working after its getting crash

### ISSUE THREAD

**Issue by dineshkumarappdeveloper** [fbsamples/account-kit-samples-for-android#27]
Its not first time im always failed to integrate AccountKit

If i start new project and i did account kit integration as my first work means its working awesome. If i integrate it with my existing project, Its not working. 

So , Now i create new project working well... okay... after i coded more its not working..
Here i Launch the AccountKit Activity in seperate activity I did not made any changes after the successful work in that activity 

The error shows while its launching..

here is the error

`06-27 13:21:25.506 2071-2071/com.ahzimat.clicks E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ahzimat.clicks, PID: 2071
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/Auth;
        at com.facebook.accountkit.ui.AccountKitActivity.onCreate(AccountKitActivity.java:281)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
        at android.app.ActivityThread.access$800(ActivityThread.java:156)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:211)
        at android.app.ActivityThread.main(ActivityThread.java:5371)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:945)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:740)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.api.Auth" on path: DexPathList[[zip file "/data/app/com.ahzimat.clicks-2/base.apk", zip file "/data/app/com.ahzimat.clicks-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.ahzimat.clicks-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.ahzimat.clicks-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.ahzimat.clicks-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.ahzimat.clicks-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.ahzimat.clicks-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.ahzimat.clicks-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.ahzimat.clicks-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.ahzimat.clicks-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.ahzimat.clicks-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.ahzimat.clicks-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.facebook.accountkit.ui.AccountKitActivity.onCreate(AccountKitActivity.java:281) 
        at android.app.Activity.performCreate(Activity.java:5990) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442) 
        at android.app.ActivityThread.access$800(ActivityThread.java:156) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:211) 
        at android.app.ActivityThread.main(ActivityThread.java:5371) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:945) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:740) 
    	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.auth.api.Auth
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 15 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
`

**Comment by nur-mukhidin** [comment]
Please use 'com.facebook.android:account-kit-sdk:4.23.0' instead of 'com.facebook.android:account-kit-sdk:4.+'

**Comment by amit2amitsoni** [comment]
Thanks @nur-mukhidin , u saved ky time. Thank you so much

**Comment by tbanj** [comment]
Thanks @nur-mukhidin , u saved ky time. iT WORKED
