### ISSUE TITLE
Crash in FB account Kit

### ISSUE THREAD

**Issue by akhgupta** [fbsamples/account-kit-samples-for-android#3]
I am not sure of steps, this is reported in crashlytics

Fatal Exception: java.util.concurrent.RejectedExecutionException: Task com.facebook.accountkit.internal.AppEventsLogger$1@42e821f8 rejected from java.util.concurrent.ThreadPoolExecutor@4290ca10[Running, pool size = 128, active threads = 128, queued tasks = 10, completed tasks = 813]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:1979)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:786)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1307)
       at com.facebook.accountkit.internal.AppEventsLogger.logSdkEvent(AppEventsLogger.java:169)
       at com.facebook.accountkit.internal.InternalLogger.logImpression(InternalLogger.java:140)
       at com.facebook.accountkit.internal.AccountKitController$Logger.logUIPhoneLogin(AccountKitController.java:204)
       at com.facebook.accountkit.ui.AccountKitActivity.logContentControllerDismissed(AccountKitActivity.java:655)
       at com.facebook.accountkit.ui.AccountKitActivity.onContentControllerDismissed(AccountKitActivity.java:645)
       at com.facebook.accountkit.ui.AccountKitActivity.backPressed(AccountKitActivity.java:539)
       at com.facebook.accountkit.ui.AccountKitActivity.onKeyDown(AccountKitActivity.java:461)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2869)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2430)
       at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:241)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2169)
       at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:4426)
       at android.view.ViewRootImpl.handleImeFinishedEvent(ViewRootImpl.java:4355)
       at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3311)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5283)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by olgaikuznetsova** [comment]
This is the Github project for the sample only, this looks like it could be an issue with the AccountKitSDK. If there is an error or crash for you you can file them into Facebook's platform bugs here: https://developers.facebook.com/bugs/ which we can diagnose and solve from there.
