### ISSUE TITLE
at com.facebook.accountkit.ui.CustomLinkMovement.onTouchEvent(CustomLinkMovement.java:59)

### ISSUE THREAD

**Issue by xiaoniudonghe2015** [fbsamples/account-kit-samples-for-android#30]
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=http://callapps.studio/privacypolicy.html cmp=com.mxtech.videoplayer.ad/com.mxtech.videoplayer.ActivityWebBrowser (has extras) } from ProcessRecord{1706df47 6925:***/u0a299} (pid=6925, uid=10299) not exported from uid 10067
	at android.os.Parcel.readException(Parcel.java:1546)
	at android.os.Parcel.readException(Parcel.java:1499)
	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2483)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1496)
	at android.app.Activity.startActivityForResult(Activity.java:3760)
mentActivity.java:859)
	at android.app.Activity.startActivity(Activity.java:4033)
	at android.app.Activi
	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
	at android.app.Activity.startActivityForResult(Activity.java:3721)
	at android.support.v4.app.FragmentActivity.startActivityForResult(Fra
gty.startActivity(Activity.java:3999)
	at android.text.style.URLSpan.onClick(URLSpan.java:62)
	at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:217)
	at com.facebook.accountkit.ui.CustomLinkMovement.onTouchEvent(CustomLinkMovement.java:59)
	at android.widget.TextView.onTouchEvent(TextView.java:8017)
	at android.view.View.dispatchTouchEvent(View.java:8481)
wGroup.dispatchTouchEvent(ViewGroup.java:2132)
	at android.view.ViewGroup.dis
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2438)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2132)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2438)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2132)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2438)
	at android.view.Vi
epatchTransformedTouchEvent(ViewGroup.java:2438)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2132)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2438)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2132)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2438)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2132)
chEvent(ViewGroup.java:2132)
	at android.view.ViewGroup.dispatchTransformedTo
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2438)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2132)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2438)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2132)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2438)
	at android.view.ViewGroup.dispatchTo
uuchEvent(ViewGroup.java:2438)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2132)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2438)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2132)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2386)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1730)
Impl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
	a
	at android.app.Activity.dispatchTouchEvent(Activity.java:2757)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2347)
	at android.view.View.dispatchPointerEvent(View.java:8681)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
	at android.view.ViewRoo
tt android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
oid.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5791)
	at a
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5817)
	at and
rndroid.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5762)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5907)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5345)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)

**Comment by xiaoniudonghe2015** [comment]
com.facebook.android:account-kit-sdk:4.24.0
com.facebook.android:facebook-android-sdk:4.28.0
