### ISSUE TITLE
Crash after OTP is sent to mobile number

### ISSUE THREAD

**Issue by rnkdsh** [fbsamples/account-kit-samples-for-android#38]
Device: Moto C Plus
OS: Android 7.0
Account Kit Version: 4.39.0

---------------------------------------------------------------------------------------------------------------------------------

Process: com.XXX.app, PID: 1204
    java.lang.NullPointerException: Attempt to read from field 'int com.facebook.accountkit.ui.PhoneCountryCodeAdapter$ValueData.position' on a null object reference
        at com.facebook.accountkit.ui.PhoneContentController$TopFragment.updateFlag(PhoneContentController.java:435)
        at com.facebook.accountkit.ui.PhoneContentController$TopFragment.access$700(PhoneContentController.java:204)
        at com.facebook.accountkit.ui.PhoneContentController$TopFragment$2.afterTextChanged(PhoneContentController.java:334)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:8566)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10775)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1236)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:592)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:524)
        at com.facebook.accountkit.ui.PhoneNumberTextWatcher.afterTextChanged(PhoneNumberTextWatcher.java:73)
        at com.facebook.accountkit.ui.PhoneContentController$TopFragment$2.afterTextChanged(PhoneContentController.java:317)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:8566)
        at android.widget.TextView.setText(TextView.java:4556)
        at android.widget.TextView.setText(TextView.java:4385)
        at android.widget.EditText.setText(EditText.java:95)
        at android.widget.TextView.setText(TextView.java:4360)
        at com.facebook.accountkit.ui.PhoneContentController$TopFragment.setPhoneNumberText(PhoneContentController.java:450)
        at com.facebook.accountkit.ui.PhoneContentController$TopFragment.onViewReadyWithState(PhoneContentController.java:364)
        at com.facebook.accountkit.ui.ViewStateFragment.onActivityCreated(ViewStateFragment.java:66)
        at com.facebook.accountkit.ui.PhoneContentController$TopFragment.onActivityCreated(PhoneContentController.java:204)
        at android.app.Fragment.performActivityCreated(Fragment.java:2361)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1014)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
        at android.app.BackStackRecord.popFromBackStack(BackStackRecord.java:1747)
        at android.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1637)
        at android.app.FragmentManagerImpl$2.run(FragmentManager.java:570)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by khp** [comment]
Thanks for reporting. This has been fixed in v4.40.

**Comment by rnkdsh** [comment]
> Thanks for reporting. This has been fixed in v4.40.

I think v4.40 is not available to use yet?

**Comment by rnkdsh** [comment]
@khp Can you please tell me when the new version will be available? I'm stuck!
