### ISSUE TITLE
Account kit Login activity is not opening got this exceptions.

### ISSUE THREAD

**Issue by patelvishal1401** [fbsamples/account-kit-samples-for-android#4]
It is working on some device like after android 5.0

Got mazer issue in android 4.0  

java.lang.RuntimeException: Unable to start activity ComponentInfo{abc.co.com/com.facebook.accountkit.ui.AccountKitActivity}: android.view.InflateException: Binary XML file line #26: Error inflating class TextView
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                    Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class TextView
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                       at com.facebook.accountkit.ui.LoginFragment.onCreateView(LoginFragment.java:38)
                                                                       at com.facebook.accountkit.ui.TitleFragmentFactory$TitleFragment.onCreateView(TitleFragmentFactory.java:42)
                                                                       at android.app.Fragment.performCreateView(Fragment.java:1700)
                                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
                                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
                                                                       at android.app.BackStackRecord.run(BackStackRecord.java:684)
                                                                       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
                                                                       at android.app.Activity.performStart(Activity.java:5240)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2168)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                                    Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
                                                                       at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:464)
                                                                       at android.view.View.<init>(View.java:3787)
                                                                       at android.widget.TextView.<init>(TextView.java:623)
                                                                       at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:59)
                                                                       at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:55)
                                                                       at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1013)
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1072)
                                                                       at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                       at com.facebook.accountkit.ui.LoginFragment.onCreateView(LoginFragment.java:38) 
                                                                       at com.facebook.accountkit.ui.TitleFragmentFactory$TitleFragment.onCreateView(TitleFragmentFactory.java:42) 
                                                                       at android.app.Fragment.performCreateView(Fragment.java:1700) 
                                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890) 
                                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062) 
                                                                       at android.app.BackStackRecord.run(BackStackRecord.java:684) 
                                                                       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447) 
                                                                       at android.app.Activity.performStart(Activity.java:5240) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2168) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)

**Comment by olgaikuznetsova** [comment]
This is the github page for the AccountKitSample project, not AccountKit. You can file any potential bugs with Platform bugs - https://developers.facebook.com/bugs/

Are you using higher than API version 15? Account Kit only supports API 15+, and if you're saying this is Android 4.0 this might be version 14 - https://developer.android.com/about/versions/android-4.0.html

**Comment by patelvishal1401** [comment]
Got solution before two hours by just updating account kit sdk.

**Comment by amanjeetsingh150** [comment]
@patelvishal1401 on which version of Account kit you shifted and this Exception was solved. I am also getting this error. It would be great if you can share the account kit SDK version at which this was fixed.

**Comment by patelvishal1401** [comment]
Hi, Update with latest account kit SDK, Thats set.

**Comment by girubhai** [comment]
@patelvishal1401 its again occur in latest release 4.35.0
`'com.facebook.android:account-kit-sdk:4.35.0'
`

> UnsupportedOperationException (@TypedArray:getDimensionPixelSize:720) {Crash Report Thread:main Exception:java.lang.RuntimeException: Unable to resume activity {com.myapp/com.facebook.accountkit.ui.AccountKitActivity}: android.view.InflateException: Binary XML file line #26: Binary XML file line #26: Error inflating class TextView at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3450) at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3490) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2749) at android.app.ActivityThread.-wrap12(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6165) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) Caused by: android.view.InflateException: Binary XML file line #26: Binary XML file line #26: Error inflating class TextView Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class TextView Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 37 to dimension: type=0x1 at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:720) at android.view.View.<init>(View.java:4458) at android.widget.TextView.<init>(TextView.java:710) at android.widget.TextView.<init>(TextView.java:704) at android.support.v7.widget.AppCompatTextView.<init>(Unknown Source) at android.support.v7.widget.AppCompatTextView.<init>(Unknown Source) at android.support.v7.app.AppCompatViewInflater.createTextView(Unknown Source) at android.support.v7.app.AppCompatViewInflater.createView(Unknown Source) at android.support.v7.app.AppCompatDelegateImplV9.createView(Unknown Source) at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(Unknown Source) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) at android.view.LayoutInflater.inflate(LayoutInflater.java:518) at android.view.LayoutInflater.inflate(LayoutInflater.java:426) at com.facebook.accountkit.ui.an.a(Unknown Source) at com.facebook.accountkit.ui.v.onCreateView(Unknown Source) at com.facebook.accountkit.ui.an.onCreateView(Unknown Source) at android.app.Fragment.performCreateView(Fragment.java:2353) at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995) at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171) at android.app.BackStackRecord.run(BackStackRecord.java:816) at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1580) at android.app.FragmentController.execPendingActions(FragmentController.java:371) at android.app.Activity.performResume(Activity.java:6813) at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3427) at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3490) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2749) at android.app.ActivityThread.-wrap12(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6165) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) }

**Comment by honeycomb25** [comment]
Hey have you been able to find solution. Getting the same error on Android 5.0.

implementation 'com.facebook.android:account-kit-sdk:4.+'

Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class TextView
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
        at android.view.LayoutInflater.inflate(<Xposed>)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at com.facebook.accountkit.ui.TitleFragmentFactory$TitleFragment.createView(TitleFragmentFactory.java:87)
        at com.facebook.accountkit.ui.LoginFragment.onCreateView(LoginFragment.java:43)
        at com.facebook.accountkit.ui.TitleFragmentFactory$TitleFragment.onCreateView(TitleFragmentFactory.java:50)
        at android.app.Fragment.performCreateView(Fragment.java:2069)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:899)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1072)
        at android.app.BackStackRecord.run(BackStackRecord.java:852)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1478)
        at android.app.Activity.performResume(Activity.java:6189)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3211)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3257) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2600) 
        at android.app.ActivityThread.access$800(ActivityThread.java:178) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5631) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102) 
     Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:572)
        at android.content.res.XResources$XTypedArray.getDimensionPixelSize(XResources.java:1352)
        at android.view.View.<init>(View.java:4038)
        at android.widget.TextView.<init>(TextView.java:663)
        at android.widget.TextView.<init>(TextView.java:658)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:76)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:72)
        at android.support.v7.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:176)
        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:101)
        at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1035)
        at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1092)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334) 
        at android.view.LayoutInflater.inflate(<Xposed>) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at com.facebook.accountkit.ui.TitleFragmentFactory$TitleFragment.createView(TitleFragmentFactory.java:87) 
        at com.facebook.accountkit.ui.LoginFragment.onCreateView(LoginFragment.java:43) 
        at com.facebook.accountkit.ui.TitleFragmentFactory$TitleFragment.onCreateView(TitleFragmentFactory.java:50) 
        at android.app.Fragment.performCreateView(Fragment.java:2069) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:899) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1072) 
        at android.app.BackStackRecord.run(BackStackRecord.java:852) 
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1478) 
        at android.app.Activity.performResume(Activity.java:6189) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3211) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3257) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2600) 
        at android.app.ActivityThread.access$800(ActivityThread.java:178) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5631) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by patelvishal1401** [comment]
Use latest account kit sdk.

**Comment by honeycomb25** [comment]
`implementation 'com.facebook.android:account-kit-sdk:4.36.0'`

Same crash Android 5.0

**Comment by xiaoniudonghe2015** [comment]
implementation 'com.facebook.android:account-kit-sdk:4.37.0'
Same crash still remain
